_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.8.10
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.8.10
            "5": 0.19.4
            "8":
                - 5
            "12": 0.19.4
            "13": linux-x86_64
gamma:
    value: 0.98
hidden_dim:
    value: 128
learning_rate:
    value: 0.001
num_episodes:
    value: 40000
